#  https://gohugo.io/getting-started/configuration/#configure-blackfriday

baseURL: https://linianhui.github.io/
languageCode: zh-cn
hasCJKLanguage: true

title: lnh blog
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
uglyURLs: false
relativeURLs: false
canonifyURLs: false

taxonomies:
  tags: tags

contentDir: blog
layoutDir: .hugo/layout
staticDir: .hugo/static
assetDir: .hugo/asset
resourceDir: .hugo/resource
dataDir: .hugo/data
themesDir: .hugo/theme
publishDir: .www

metaDataFormat: yaml
frontmatter:
  date: 
    - created_at
summaryLength: 120

pygmentsCodefences: true
pygmentsUseClassic: false
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: false
pygmentsStyle: vs
pygmentsOptions:
  noclasses: true
  linenos: 1
  linenostart: 1

enableEmoji: true
enableGitInfo: true

# Blackfriday Options 
taskLists: true
smartypants: false
angledQuotes: false
fractions: true
plainIDAnchors: false
extensions:
  - tables
  - fencedCode
  - autolink
  - strikethrough
  - spaceHeaders
  - footnotes
  - headerIds
  - definitionLists
  - joinLines
extensionsmask:
  - noIntraEmphasis
  - laxHtmlBlocks
  - tabSizeEight
  - noEmptyLineBeforeBlock
  - autoHeaderIds
  - backslashLineBreak
skipHTML: true
hrefTargetBlank: true

params:
  RepositoryUrl: https://github.com/linianhui/linianhui.github.io
  RepositoryBlogUrl: https://github.com/linianhui/linianhui.github.io/blob/blog/blog

log: true
verbose: true
