version: 1.0.{build}
image: Ubuntu1804
build: off
branches:
  only:
    - blog
before_test:
  - apt-get update -y && apt-get install hugo -y
test_script:
  - hugo --config .hugo.yml

artifacts:
  - path: .www