version: 1.0.{build}
image: Ubuntu1804
build: off
branches:
  only:
    - master
test_script:
  - nvm list
  - nvm use 8.16.0
  - nvm list
  - npm install -g hexo-cli
  - npm install
  - npm run pack
