version: 1.0.{build}
image: Ubuntu1804
build: off
branches:
  only:
    - blog

install:
  - sh: sudo apt-get update -y 
  - sh: sudo apt-get install hugo -y

test_script:
  - hugo --config .hugo.yml

artifacts:
  - path: .www