version: 1.0.{build}
image: Ubuntu1804
build: off
branches:
  only:
    - blog

environment:
  private_key:
    secure: HkVeTPVg2imqsC41BoDdXhl4uY6CL5vSmqPjPae7GF1OWgLgucKKbgT+8rKVF/TVVGxB5Sq3IbZ8CHgrr4eGYBV8AHrZaaGA1O9iaC1uT7QQW7kf/okB65IR7m2urFv/n2k1fRJaSNEhWtS6GKACobRUnW2YJ2niQIPuDgBaAWiffQiLjlJfmKPjVIJuGu6iRGUr812UlLdemPwz23lLr/Kd5dHYel5gPf49GWL82WTlI7h39j7Gy1A/sT30gBn+Xdm5xasIMqnYNmEcbqUwDOQoYh9vdF40r2FBI8Z43phOd5G2bXcSBTn9eETx4TejAMUpnqAytfyjoIvIeS/mtQZQaxfMZmiDpLt00K16cN8x2vJ0s+Rluw/aPn7kpnpy6iH7jOSNCTzP2uIXnRN+X9S9pqsKHYuz9ock909Oa06t4bfDv6o6gdD3/jsI4MotRCVw4tOWnDXnjItB9yPv6gZuZSLRY+WNlF+4cnNXFSazPFWrFPxbrOeBcKXodYGA7KcqCNl7dq07lROxcaGUGd95MeImj12qBiE/MXzsIk3NgsrwS0BD60m/CQ5KnpBYV2tcvYPE3lh2tI79miemGd6T8JqEgK6KSrLqGs6DknjA6v21KCUOyLrSlLtPL/Zg/JpDjrXZvbrCEaWlmF8EAzz+MEbaDnbXiIWpi8JG4SEkVEaHlUTJWkB8KyScPxoqljtfeRUy0Ormu4W4i/4fgp3WIhe3RrYl9tz7h5csp5jyEmN2x3+6RCEg9BiQqKHCtvSmYvryjQ5saLFTrHTdXjTAmLEsN+fi6gCPAAyktwoP8zy1RWJbcoj/0yHFVCZgAzYkRewgZg5L4ImIbuYEUg61uMfstTh5tHxWXONeU9QXeNW9ofUgEvZ/GiSSKBTVrfuU6Ejd6c4czTu1qMxmUtleXfY7GSZ9PGdvdLOLTLIyEcqJQ+0w1TJRMAMxdmBWB4nlDEn9Huw2cfMmI0S1f/YbQPUpY4bc7Ec0QiJTDLhr86rINlktcnUq6VlNS9dIrjOwAFM9VRfPk8fwN+1OEIEo+ljYMxsFmJJtUWqfOmMolupkaXBA9YHjCVC0m73x7QMH2e9cDWwxTVXPbzYw5yWpCVNolOoLRDsL286MjbFon4iHiB9YoAGI6R3RLtIXEDW/dsAd/RsGcrrjtUDFeqn4ddnldmifhhpXd48RVJIw1nzB3rY/bHXQOD+tpkl0gkEXCDyz/v/P6l50/uoomWpt0/7I6updCQemnCtKNYKZr+UQEjA2dEq6nm5BAZqvsr7c7cGEEgHqEa5IHNPmKPUGQIyOe309zD8X9uCTo0G3wUN54k39e39zOyFPJX4BMvaua3F6PH833RdkR6RiTfjGg/hbT8xj1HFyW6P2x2OY+oBgarmruk5cMuveZ8Wsgi/2qb7VZ+gH4xmljqMayqwUMDj9/zEGGvVN1cnJaraoZqchitk1l5V4UUCsVxax3kV5sviZyivstD/PuV67CDBX9UPwzsTLe+bg43n2h5ECJf+/bBVW2h8NbgJpHzF4c+DheSD7h1Gc0DU9lMRniGRll61sevRvOQY7qgeuZPkOk6m+xmY+9qtT+OxI7COIqAapV1mXIoGPa+aKkm03unIx1v4yBz0u/8wYiVXx1Mj8FUMRJIFc2Y+lj3jB73Jjiupar7Mmp62fPmG71Rdg5oXQVPrR0VhZiRf/+DAD1SF2wlHzJHKZeAKtUXAjr4CgfJhWZ3vzECbVL/ejMnP/ntzq6Wd50TSUQtKfRcw3C5vMEGJIVGZWqUJz4VrIsIHK9fSEoyF4bTniDVc7WW3/8FdpjzG1vGr5eE3nxo3WKl8Hb33/1nL6DWXPMwzISG6qTTNtL0AfgZUBNlf2sXj9MCmzIdp2WADeQ2Y8YjyELuDokUNvjW3MPh7EvmVUNveW2Z3S2mNei0vcivxAB8nyuBZWeNwb5sVaRm3xr7SFNx8fguvgZS9xPdEZE3iAxT0lzy6b5unR9DZ2PWXCrNWPVFSgQzXP37QCDMZjst37ocZ2Akt0nML7SVj3dxk6OIEXNA9ZMeoO8ztKBfNn6xoXtDJrqm9hatmODHNTLrfImAmTmTtEqe1m3ad9d1MXt+H0cr34RsDhAoiqFsdZ7dnBsY85tQBg16CdhYTvHemoLzAWBnE+ycvuIa/g8xKrZb/x

install:
  - sudo apt-get update -y 
  - sudo apt-get install hugo -y
  - echo "-----BEGIN RSA PRIVATE KEY-----" > $HOME/.ssh/id_rsa
  - echo "${private_key}" | tr " " "\n" >> $HOME/.ssh/id_rsa
  - echo "-----END RSA PRIVATE KEY-----" >> $HOME/.ssh/id_rsa

test_script:
  - hugo --config .hugo.yml

deploy_script:
  - cd .www
  - git init
  - git config user.name 'appveyor'
  - git config user.email 'lnhcode@outlook.com'
  - git add .
  - git commit -m "appveyor auto deploy"
  - git remote add origin git@github.com:linianhui/linianhui.github.io.git
  - git push --set-upstream origin master --force