#  https://gohugo.io/getting-started/configuration/#configure-blackfriday

log: true
verbose: true


baseURL: https://linianhui.github.io/
languageCode: zh-cn
hasCJKLanguage: true


title: "blackheart"
params:
  Subtitle: "泛义的工具是文明的基础，而确指的工具却是愚人的器物"
  RepositoryUrl: https://github.com/linianhui/blog
  RepositorySrcUrl: https://github.com/linianhui/blog/blob/master/src
  CiUrl: https://github.com/linianhui/blog/actions
  CiBadgeImageUrl: https://github.com/linianhui/blog/workflows/deploy/badge.svg
  GitLastHash: ''

menu:
  main:
    - identifier: home
      name: 首页
      url: /
      weight: 1
      pre: '<i class="fa fa-home"></i>'
    - identifier: topic
      name: 专题
      url: /topic/
      weight: 2
      pre: '<i class="fa fa-folder"></i>'
    - identifier: tag
      name: 标签
      url: /tag/
      weight: 3
      pre: '<i class="fa fa-tags"></i>'
    - identifier: archive
      name: 归档
      url: /archive/
      weight: 4
      pre: '<i class="fa fa-archive"></i>'
    - identifier: github
      name: GitHub
      url: https://github.com/linianhui/blog
      weight: 5
      pre: '<i class="fa fa-github"></i>'
  topic: []
taxonomies:
  tag: tag
sectionPagesMenu: "topic"

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
uglyURLs: false
relativeURLs: false
canonifyURLs: false

contentDir: src
layoutDir: .hugo/layout
staticDir: .hugo/static
assetDir: .hugo/asset
resourceDir: .hugo/resource
dataDir: .hugo/data
themesDir: .hugo/theme
publishDir: .www

metaDataFormat: yaml
frontmatter:
  date:
    - created_at
summaryLength: 168
enableEmoji: true
enableGitInfo: true

markup:
  tableOfContents:
    startLevel: 1
    endLevel: 6
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: false
    noClasses: true
    style: vs
    tabWidth: 4
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: false
    parser:
      attribute: true
      autoHeadingID: false
    renderer:
      hardWraps: true
      unsafe: true
      xHTML: true
