name: deploy

on:
  push:
    branches:
      - blog

jobs:
  deploy:
    runs-on: ubuntu-latest

    container:
      # https://hub.docker.com/r/lnhcode/hugo
      image: lnhcode/hugo

    steps:
      - name: git checkout
        uses: actions/checkout@v1
      - name: hugo version
        run: hugo version
      - name: hugo generate static web site
        run: hugo --config .hugo.yml
      - name: push to github master branch
        working-directory: .www
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git init
          git config user.name 'GitHub Actions'
          git config user.email 'lnhcode@outlook.com'
          git add .
          git commit -m "GitHub Actions deploy ${GITHUB_SHA}"
          git push --force https://x-access-token:${GITHUB_TOKEN}@github.com/linianhui/linianhui.github.io.git HEAD:master
