name: deploy

on:
  push:
    branches:
      - blog

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v1

      - name: install hugo
        env:
          HUGO_VERSION: 0.62.0
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
          sudo dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb

      - name: hugo version
        run: hugo version

      - name: hugo generate static web site
        run: |
          export HUGO_PARAMS_GitLastHash=${GITHUB_SHA}
          hugo --config .hugo.yml

      - name: push to github master branch
        env:
          DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        working-directory: .www
        run: |
          mkdir -p ~/.ssh/
          echo "${DEPLOY_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git init
          git config user.name 'GitHub Actions'
          git config user.email 'lnhcode@outlook.com'
          git add .
          git commit -m "GitHub Actions deploy ${GITHUB_SHA}"
          git push --force git@github.com:${GITHUB_ACTOR}/${GITHUB_REPOSITORY} HEAD:master
