name: deploy

on:
  push:
    branches:
      - blog

jobs:
  deploy:
    runs-on: ubuntu-latest

    container:
      # https://hub.docker.com/r/lnhcode/hugo
      image: lnhcode/hugo

    steps:
      - name: git checkout
        uses: actions/checkout@v1
      - name: config git
        env:
          DEPLOY_PRIVATE_KEY: ${{secrets.DEPLOY_PRIVATE_KEY}}
        run: |
          mkdir -p ~/.ssh/
          echo "${DEPLOY_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'lnhcode@outlook.com'
      - name: hugo generate static web site
        run: |
          hugo version
          hugo --config .hugo.yml
      - name: push to github master branch
        working-directory: .www
        run: |
          git init
          git commit -am "GitHub Actions deploy ${GITHUB_SHA}"
          git push --force git@github.com:linianhui/linianhui.github.io.git HEAD:master
