name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-16.04

    steps:
      - name: git checkout
        uses: actions/checkout@v1

      - name: add deploy private key
        env:
          DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "${DEPLOY_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: install hugo
        env:
          HUGO_VERSION: 0.62.0
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb -O hugo.deb
          sudo dpkg -i hugo.deb

      - name: hugo generate static web site
        run: |
          export HUGO_PARAMS_GitLastHash=${GITHUB_SHA}
          hugo

      - name: push to linianhui/linianhui.github.io master branch
        working-directory: .www
        run: |
          git init
          git config user.name 'GitHub Actions'
          git config user.email 'lnhcode@outlook.com'
          git add .
          git commit -m "GitHub Actions Auto Deploy"
          git push --force git@github.com:/linianhui/linianhui.github.io HEAD:master
