name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    container:
      # https://hub.docker.com/r/lnhcode/hugo
      image: lnhcode/hugo:0.62.0

    steps:
      - name: git checkout
        uses: actions/checkout@v1

      - name: add deploy private key
        env:
          DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "${DEPLOY_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: hugo generate static web site
        run: |
          export HUGO_PARAMS_GitLastHash=${GITHUB_SHA}
          hugo --config .hugo.yml

      - name: push to linianhui/linianhui.github.io master branch
        working-directory: .www
        run: |
          git init
          git config user.name 'GitHub Actions'
          git config user.email 'lnhcode@outlook.com'
          git add .
          git commit -m "GitHub Actions Auto Deploy"
          git push --force git@github.com:/linianhui/linianhui.github.io HEAD:master
