name: deploy

on:
  push:
    branches:
      - blog

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: install hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.58.3/hugo_0.58.3_Linux-64bit.deb
          sudo dpkg -i hugo_0.58.3_Linux-64bit.deb
      - name: hugo generate static web site
        run: |
          hugo version
          hugo --config .hugo.yml
      - name: push to github master branch
        env:
          DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        working-directory: .www
        run: |
          mkdir -p ~/.ssh/
          echo "${DEPLOY_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git init
          git config user.name 'GitHub Actions'
          git config user.email 'lnhcode@outlook.com'
          git add .
          git commit -m "GitHub Actions deploy ${GITHUB_SHA}"
          git push --force git@github.com:linianhui/linianhui.github.io.git HEAD:master
